### ISSUE TITLE
Use this repo for Code4Lib Conference Site?

### ISSUE THREAD

**Issue by sdellis** [code4lib/code4lib.github.io#1]
Hi @cbeer -- are there any objections to using this repo (or starting a new one) for the current conference site?  Once we are satisfied with it, I'd like to change the DNS settings so that 2016.code4lib.org points to it on the web. @wickr, do you see any issues with being able to make those changes when we're ready?

**Comment by cbeer** [comment]
No strong objections, but I'd suggest we should actually create `code4lib/2016.code4lib.org` for that purpose.

**Comment by sdellis** [comment]
Hey @cbeer, we finally have a starter site.  I've transferred the repo to Code4Lib and forked it so we can continue to work in our sandbox.  We'll make pull requests to this repo when we need to.  So I know that @wickr will need to set up an ALIAS record in the code4lib.org dns, but I've only done it for repos that are titled with the "github.io" suffix like so:
```
ALIAS	2016.code4lib.org	3600		cod4lib.github.io  
```
Then we'll need to add a file called CNAME to the repo with the following text:
```
2016.code4lib.org
```
Have you done this with non-github.io repos?
