### ISSUE TITLE
Add permalinks for conference talk pages

### ISSUE THREAD

**Issue by wickr** [code4lib/code4lib.github.io#3]
For earlier conferences, each main talk would usually get it's own page, to link slides, video, etc. These are linked off the schedule that way, but the permalinks haven't been added yet.

Example:
2008 conference schedule: https://code4lib.org/conference/2008/schedule
link to "Finding Relationships in Marc Data - Rob Styles" is https://code4lib.org/conference/2008/styles
link is broken, need to find the talk page/post and add `permalink: /conference/2008/styles` to front matter

2006 and 2007 pages don't have `/conference` in most of the URLs so more may need changing.

Fixing a year's schedule, or even part of one, would help. Progress can be tracked here:

- [x] 2006
- [x] 2007
- [x] 2008
- [x] 2009
- [x] 2010
- [x] 2011
- [x] 2012
- [x] 2013
- [ ] 2014
- [ ] 2015

**Comment by kaitlinnewson** [comment]
Note that the permalinks also need to have a trailing slash, e.g:

`permalink: /conference/2008/styles/`
