### ISSUE TITLE
broken link - list of IRC users

### ISSUE THREAD

**Issue by phette23** [code4lib/code4lib.github.io#44]
this section of the IRC FAQ https://code4lib.org/irc/faq 

> ## Who will I find on #code4lib?
> There is an incomplete list of regulars [here](https://code4lib.org/node/87). This is not an official list of any kind. If you’re not on it yet, feel free to add your nick, your name, and a link to your website.

has a link to the old Drupal site at https://code4lib.org/node/87

Not sure if that list exists anywhere it can be salvaged or if it should just be removed.

**Comment by kaitlinnewson** [comment]
There's a wayback version of this here: https://web.archive.org/web/20170705035528/https://code4lib.org/node/87

Is this worthwhile to keep though? It may be outdated at this point.

**Comment by phette23** [comment]
I think it's probably worth dropping but am not too opinionated about it.
